[{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module 'react' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 52,
	"endLineNumber": 2,
	"endColumn": 59,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 18,
	"startColumn": 10,
	"endLineNumber": 18,
	"endColumn": 113,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 42,
	"startColumn": 5,
	"endLineNumber": 42,
	"endColumn": 209,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 5,
	"endLineNumber": 44,
	"endColumn": 11,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "2875",
	"severity": 8,
	"message": "This JSX tag requires the module path 'react/jsx-runtime' to exist, but none could be found. Make sure you have types for the appropriate package installed.",
	"source": "ts",
	"startLineNumber": 57,
	"startColumn": 5,
	"endLineNumber": 57,
	"endColumn": 154,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 57,
	"startColumn": 5,
	"endLineNumber": 57,
	"endColumn": 154,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 58,
	"startColumn": 7,
	"endLineNumber": 58,
	"endColumn": 87,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 60,
	"startColumn": 11,
	"endLineNumber": 60,
	"endColumn": 263,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 62,
	"startColumn": 11,
	"endLineNumber": 62,
	"endColumn": 18,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 64,
	"startColumn": 7,
	"endLineNumber": 64,
	"endColumn": 13,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 65,
	"startColumn": 5,
	"endLineNumber": 65,
	"endColumn": 11,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 74,
	"startColumn": 5,
	"endLineNumber": 74,
	"endColumn": 81,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 75,
	"startColumn": 7,
	"endLineNumber": 75,
	"endColumn": 30,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 75,
	"startColumn": 58,
	"endLineNumber": 75,
	"endColumn": 189,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 75,
	"startColumn": 194,
	"endLineNumber": 75,
	"endColumn": 201,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 75,
	"startColumn": 203,
	"endLineNumber": 75,
	"endColumn": 209,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/homee/Downloads/MilkDesign.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 76,
	"startColumn": 5,
	"endLineNumber": 76,
	"endColumn": 11,
	"modelVersionId": 7,
	"origin": "extHost1"
}]